name: An Unheralded Perspective
meta_description: "Blogging about iOS development"

#SEO
title: An Unheralded Perspective
description: Blogging about iOS development
author: Siddarth Kalra
twitter:
  username: siddarthkalra
  card: summary

markdown: kramdown
remote_theme: rosario/kasper
# highlighter: pygments
logo: false
paginate: 15
baseurl: /
# domain_name: 'http://yourblog-domain.com'
# google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
plugins:
  - jekyll-seo-tag

# Details for the RSS feed generator
# url:            'blog url'
# author:         'Your Name'
