name: An Unheralded Perspective
description: Blogging about iOS development
meta_description: "Blogging about iOS development"

markdown: kramdown
remote_theme: rosario/kasper
# highlighter: pygments
logo: false
paginate: 15
baseurl: /
# domain_name: 'http://yourblog-domain.com'
# google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
# url:            'blog url'
# author:         'Your Name'
